---

- hosts: all
  become: true
  tasks:

  - name: install httpd package
    dnf:
      name: httpd
    when: ansible_distribution == "Alma"


  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution in ["Ubuntu","Debian"]
