---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (rhe base)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Alma"

  - name: install updates (debian base)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install httpd package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Alma"

- hosts: file_servers
  become: true
  tasks:

  - name: install ftp package
    apt:
      name: ftp
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]
