- name: add ssh key for user1
  authorized_key:
    user: user1
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPMvtmlcqMmjAbyasMx3n1ZxENqhdz/9pGApMNL+xKGj ansible_key"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
